SET TIME ZONE 'UTC';

CREATE TABLE public.users (
    id              BIGINT       PRIMARY KEY,
    username        VARCHAR(100) UNIQUE NOT NULL,
    email           VARCHAR(100) UNIQUE NOT NULL,
    password_hash   VARCHAR(255) NOT NULL,
    verification_token   VARCHAR(255),
    enabled              BOOLEAN NOT NULL DEFAULT FALSE,

    CONSTRAINT valid_username CHECK (CHAR_LENGTH(TRIM(username)) > 0),
    CONSTRAINT valid_users_id CHECK (id BETWEEN 0 AND 9999)
);

CREATE TABLE public.user_groups (
    id          BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    admin_id    BIGINT       NOT NULL,
    name        VARCHAR(100) UNIQUE NOT NULL,
    created_at  TIMESTAMPTZ  NOT NULL DEFAULT NOW(),

    FOREIGN KEY (admin_id) REFERENCES public.users(id),
    CONSTRAINT valid_group_name CHECK (CHAR_LENGTH(TRIM(name)) > 0)
);

CREATE TABLE public.group_members (
    id          BIGINT      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    group_id    BIGINT      NOT NULL,
    user_id     BIGINT      NOT NULL,
    join_time   TIMESTAMPTZ NOT NULL DEFAULT NOW(),

    FOREIGN KEY (group_id) REFERENCES public.user_groups(id) ON UPDATE CASCADE ON DELETE CASCADE,
    FOREIGN KEY (user_id) REFERENCES public.users(id) ON UPDATE CASCADE ON DELETE CASCADE,
    CONSTRAINT uq_membership UNIQUE (group_id, user_id)
);

CREATE TABLE public.friendships (
    id                  BIGINT      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id_a      BIGINT      NOT NULL,
    user_id_b    BIGINT      NOT NULL,
    status      VARCHAR(10) NOT NULL DEFAULT 'PENDING',
    created_at          TIMESTAMPTZ NOT NULL DEFAULT NOW(),

    FOREIGN KEY (user_id_a) REFERENCES public.users(id) ON UPDATE CASCADE ON DELETE CASCADE,
    FOREIGN KEY (user_id_b) REFERENCES public.users(id) ON UPDATE CASCADE ON DELETE CASCADE,

    CONSTRAINT valid_direction UNIQUE (user_id_a, user_id_b),
    CONSTRAINT valid_friendships_status CHECK (
      status IN ('PENDING', 'ACCEPTED', 'REJECTED')
    ),
    CONSTRAINT different_friendship_users CHECK (user_id_a <> user_id_b)
);

CREATE TABLE public.bills (
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    group_id          BIGINT NOT NULL,
    creator_id        BIGINT NOT NULL,
    description       VARCHAR(255) NOT NULL,
    total_amount      DECIMAL(10,2) NOT NULL,
    currency          VARCHAR(3) NOT NULL DEFAULT 'EUR',
    participant_names VARCHAR(255),
    status            VARCHAR(10) NOT NULL DEFAULT 'COMPLETED',
    created_at        TIMESTAMPTZ NOT NULL DEFAULT NOW(),

    FOREIGN KEY (group_id)
        REFERENCES public.user_groups(id)
        ON UPDATE CASCADE
        ON DELETE CASCADE,

    FOREIGN KEY (creator_id)
        REFERENCES public.users(id)
        ON UPDATE CASCADE
        ON DELETE RESTRICT,

    CONSTRAINT positive_bills_amount
        CHECK (total_amount > 0),

    CONSTRAINT valid_bill_status
        CHECK (status IN ('PENDING', 'COMPLETED', 'DELETED')),

    CONSTRAINT valid_currency_code
        CHECK (CHAR_LENGTH(TRIM(currency)) = 3)
);


CREATE TABLE public.expense_splits (
    id          BIGINT        GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id     BIGINT        NOT NULL,
    group_id    BIGINT        NOT NULL,
    total_owed  DECIMAL(10,2) NOT NULL DEFAULT 0.00,
    total_paid  DECIMAL(10,2) NOT NULL DEFAULT 0.00,

    CONSTRAINT no_duplicate_membership UNIQUE (user_id, group_id),
    FOREIGN KEY (user_id) REFERENCES public.users(id) ON UPDATE CASCADE ON DELETE CASCADE,
    FOREIGN KEY (group_id)REFERENCES public.user_groups(id) ON UPDATE CASCADE ON DELETE CASCADE,
    CONSTRAINT positive_total_owed CHECK (total_owed >= 0),
    CONSTRAINT positive_total_paid CHECK (total_paid >= 0)
);

CREATE TABLE public.settlements (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    group_id        BIGINT NOT NULL,
    debtor_id       BIGINT NOT NULL,
    creditor_id     BIGINT NOT NULL,
    amount          DECIMAL(10,2) NOT NULL,
    status          VARCHAR(10) NOT NULL DEFAULT 'CONFIRMED',
    confirmed_by_id BIGINT NOT NULL,
    created_at      TIMESTAMPTZ NOT NULL DEFAULT NOW(),

    FOREIGN KEY (group_id)
        REFERENCES public.user_groups(id)
        ON UPDATE CASCADE
        ON DELETE CASCADE,

    FOREIGN KEY (debtor_id)
        REFERENCES public.users(id)
        ON UPDATE CASCADE
        ON DELETE RESTRICT,

    FOREIGN KEY (creditor_id)
        REFERENCES public.users(id)
        ON UPDATE CASCADE
        ON DELETE RESTRICT,

    FOREIGN KEY (confirmed_by_id)
        REFERENCES public.users(id)
        ON UPDATE CASCADE
        ON DELETE RESTRICT,

    CONSTRAINT positive_settlement_amount
        CHECK (amount > 0),

    CONSTRAINT different_settlement_users
        CHECK (debtor_id <> creditor_id),

    CONSTRAINT valid_settlement_status
        CHECK (status IN ('CONFIRMED', 'REVERTED')),

    CONSTRAINT valid_settlement_confirmer
        CHECK (
            confirmed_by_id = debtor_id
            OR confirmed_by_id = creditor_id
        )
);
